project:
  type: manuscript
  output-dir: docs

title: "Ambiguit√§t in Organisationen"
site-url: "https://ambiguitaet.sukstorf.de"

website:
  google-analytics: "G-E5JTBN5NH8"   # <-- HIER deine GA4 ID eintragen

execute:
  freeze: auto
  echo: true

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    number-sections: true
    comments:
      hypothesis: true
    include-after-body: citation-footer.html

  pdf:
    toc: true
    number-sections: true
    number-tables: true
    keep-tex: true
    biblio-style: authoryear
    cite-method: biblatex


